server:
  port: 9527

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/simple?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 120000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      pool-name: MyHikariCP
      auto-commit: true
  flyway:
    out-of-order: true
    baseline-on-migrate: true

  jpa:
    show-sql: true
    generate-ddl: false

  session:
    timeout: 30s
  mvc:
    async:
      request-timeout: 30s

simple:
  security:
    image-code:
      length: 4
      expire-in: 1200
    sms-code:
      length: 4
      expire-in: 1200